project:
  render:
    - "*.qmd"
    - "!/Templates"
    - "!/Data"
    - "!/Images"
    - "!/Projects/Archive"
  type: website
  output-dir: docs

website:
  title: "Diego Chuquimia - Portfolio"
  favicon: images/favicon.png
  back-to-top-navigation: true
  page-footer: 
    border: true
    left: "Diego Chuquimia 2026©"
    right: 
      - icon: telephone
        href: "tel:+15717767092"
      - icon: envelope
        href: mailto:chuquimiadiego@gmail.com
      - icon: calendar
        href: https://calendly.com/chuquimiadiego/professional-meeting
      - icon: linkedin
        href: https://linkedin.com/in/diegoach
      - icon: github
        href: https://github.com/diegouschq

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "About me"
        file: about.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Licenses & Certifications"
        file: certification.qmd  
      - text: "Projects"
        file: project_index.qmd
      - text: "Letter of Recomnedations"
        file: recommendation.qmd

  sidebar:
    - title: "Portfolio"
      contents:
        - text: "Home"
          file: index.qmd
        - text: "---"
        - text: "My Resume"
          file: resume.qmd
        - text: "---"
        - text: "About Me"
          file: about.qmd
        - text: "---"
        - text: "License & Certification"
          file: certification.qmd
        - text: "---"
        - text: "Projects Overview"
          file: project_index.qmd
        - text: "---"
        - text: "Letter of Recomnedations"
          file: recommendation.qmd
        - text: "---"
        
format:  
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
