---
title: "Project Index"
---


### [Excel Projects](project/Excel/excel.qmd)

Excel projects using formulas, Pivot Tables, dashboards, and financial reports.

* [Connecting Historical Records Using Bayesian Analysis](project/Excel/familysearch/familysearch.qmd)

Family Search project implementing a Bayesian analysis and data skills.


### Power BI Projects
Data analysis, dashboards, and reports built with Power BI.

* [Quantifying Faith: Religious Data Insights](project/PowerBI/religion_survey/religion.qmd)

This project analyzed and interpreted religious data to better understand trends, beliefs, and practices within a spiritual context.

### SQL

Projects using SQL to clean, summarize, and analyze business and financial data.

* [Financial Research in Airbnb California](project\SQL\finance_airbnb\finance.qmd)

Evaluates rental pricing, demand patterns, and overall market profitability across San Diego.


### RStudio

Projects using R, tidyverse, ggplot2, Quarto, maps, and statistical analysis.

* [Housing Market Price Trend Analysis](project/R/rent/rent.qmd)

Study of the housing market in Rexburg, Idaho.

* [Analyzing San Diego Airbnb Prices and Profits](project/R/airbnb/airbnb.qmd)

Market Research of Airbnb in San Diego Area.

### AI Essentials

Personal and customize implementations with AI for personal tasks and community implementations.

* [Developing Community Learning Assistants Using Custom GPTs](project/AI/Dax/dax.qmd)

Designing specialized GPTs to support community learning in coding learning experience with DAX, language acquisition, and DMV exam preparation.


### UX Design

* [Personal Portfolio Website: From Concept to Interactive Prototype](project/UX/portfolio.qmd)

An end-to-end UX design case study documenting the creation of a recruiter-focused personal portfolio website, moving from initial site architecture and user flows to interactive Figma wireframes and high-fidelity prototypes.

