---
title: Diego Chuquimia's CV
editor: 
  markdown: 
    wrap: 72
---
# Diego Andres Chuquimia Quiroz

::: {#webaddress}
<a href="mailto:chuquimiadiego@gmail.com">chuquimiadiego\@gmail.com</a> \|
(571) 7767092 \|
<a href="https://linkedin.com/in/diegoach">linkedin.com/in/diegoach</a> \|
<a href="https://dot.cards/diegoch">dot.cards/diegoch</a>
:::

Economics student with experience in financial analysis, operational reporting, and business intelligence tools including Power BI, Excel, SQL, and R. Skilled in dashboard development, data validation, and statistical analysis with a strong interest in financial systems, forecasting, and enterprise analytics.


## Core Competencies

**Certifications:** Data Science, Excel and Power BI – Data Analysis and Visualization, SQL for Finance, Alteryx for Financial Services, Essential Power Automate, AI Generative Essentials.

**Excel & Data Visualization:** Pivot Tables, XLOOKUP/VLOOKUP, SUMIFS, COUNTIF, reporting automation dashboards, data visualization, and charts

**Business Intelligence Tools:** Advanced Excel, Power BI, Tableau, Interactive Dashboards, KPIs, Forecasting, Management Reports, and Data-driven Decisions.

**Programming & Tools:** SQL, Python, and R.

**Languages:** Spanish, fluent.


## Education

**Brigham Young University - Idaho** 
**Bachelor of Science in Economics | Data Science minor** 

- Marketing Director at Economics Society 
- Relevant coursework: Business Analytics, Labor Economics, Law & Economics, Behavioral Economics, and Data Wrangling and Visualization.


## Experience

`July 2024 - September 2025`
**Degree Verification Specialist**, *Brigham Young University - Idaho*, Rexburg, Idaho

- Created and reviewed degree evaluation reports, maintaining 100% accuracy in awarding processes and ensuring data integrity across student records.
- Utilized Excel and CX platforms to examine and validate 100+ student data across academic programs, generating tracking reports to improve degree completion and support data-driven decisions.

`March 2025 - September 2025`
**Peer Academic Mentor**, *Brigham Young University - Idaho*, Rexburg, Idaho

- Conducted and compiled detailed research on 25+ academic programs and industry certifications, supporting students in making informed decisions aligned with career market trends and salary benchmarks.
- Trained peers using 20+ student cases and cooperated cross-functionally to improve accuracy and consistency in degree audit reviews.

`August 2019 - December 2019`
**Logistics Assistant**, *Bountiful Corp, Auditing Firm*, Santa Cruz, Bolivia

- Audited and reconciled over 100 vendor and contractor transactions against financial reports to ensure accurate expense tracking and contract compliance.

- Conducted financial analysis using Advanced Excel to ensure accuracy in financial records, validate balance sheets, and financial statements.



## Projects

`May 2026`

**Quantifying Faith: Religious Data Insights**

*Power BI, DAX, Microsoft Forms, Data Integration, Dashboard Development*

- Analyzed over 1,000 survey responses, implemented DAX measures, and transformed data to reveal behavioral trends in tolerance, commitment, and demographic groups.

- Identify an age-related gap between younger groups having higher rates of nonreligious identification and recommend religious organizations promoting engagement.



`December 2025`

**Housing Market Price Trend Analysis**

*R, Advanced Excel, Statistical Modeling, Regression Analysis, ANOVA*

- Analyzed 108 multi-year housing pricing data points using R and Excel to identify financial trends and cost patterns across property management companies.
- Executed statistical analysis, including mean price comparisons, ANOVA testing, and linear regression modeling, to evaluate pricing changes over time.
- Identified pricing outliers and interpreted market trends using quantitative analysis and financial data visualization techniques.



`May 2026`
**Financial Research in Airbnb San Diego - California	April 2026**

*SQL, R, Excel, Data Integration, Risk Modeling & Financial Analysis*

- Developed a market research report analyzing revenue gaps and growth potential which estimated a 54.99 higher revenue percentage for entire homes and 132.79 percent for private rooms.

- Synthesized market research into actionable business insights for real estate investment strategies, highlighting optimal property categories and neighborhood submarkets to maximize return on investment.



`August 2026`
**Connecting Historical Records Using Bayesian Method**

*Bayesian Analysis, Record Linkage, Advance Excel, Data Integration, and Risk Modeling*

- Developed a Bayesian model to evaluate 405 historical records by applying likelihood records ratios and sequential probability updates across identity and family attributes.

- Ranked potential matches and identified a candidate with 75 posterior probability percentage for matching the main individual.



`August 2026`
**Social Media Growth Strategy & Product Launch Analysis**	

*Excel, AI Generative, Financial Modeling, Customer Acquisition Consumption, Project Management*

- Designed a targeted Reels strategy by analyzing Instagram engagement data, optimizing content for peak viewing windows to drive naturally growing an audience from 18 to 35-year-old.

- Modeled financial evaluation cost, CAC, and opportunity cost to support product launch, and built a Power Automate email to keep customer communication.



```{=html}
<!-- ### Footer
Last updated: June 2026 -->
```